In [3]:
import pandas as pd
import numpy as np

# Exploramos las caracter√≠sticas de los datos:

In [6]:
#traemos el ultimo DF guardado

df = pd.read_csv('C:/Users/User/Proyecto Coder/data/processed/df_merged.csv')
df.drop('Unnamed: 0', axis=1 ,inplace=True)
df

,customerID,gender,SeniorCitizen,Partner,Dependents,Edad,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,27,No phone service,DSL,No,Yes,...,No,No,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,57,No,DSL,Yes,No,...,No,No,34,Yes,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,18,No,DSL,Yes,Yes,...,No,No,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,18,No phone service,DSL,Yes,No,...,No,No,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,24,No,Fiber optic,No,No,...,No,No,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,18,Yes,DSL,Yes,No,...,Yes,Yes,24,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,43,Yes,Fiber optic,No,Yes,...,Yes,Yes,72,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,25,No phone service,DSL,Yes,No,...,No,No,11,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,18,Yes,Fiber optic,No,No,...,No,No,4,Yes,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,18,No,Fiber optic,Yes,No,...,Yes,Yes,66,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

## Visualizamos la info de las variables:

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   Edad              7043 non-null   int64
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  tenure            7043 non-null   int64
 15  PhoneService      7043 non-null   object
 16  Contract          7043 non-null   object
 17  PaperlessBilling  7043 non-null   object
 18  PaymentMethod     7043 non-null   object
 19  MonthlyCharges    7043 non-null   float64
 20  TotalCharges      7043 non-null   float64
 21  Churn             7043 non-null   object
dtypes: float64(2), int64(3), object(17)
memory usage: 1.2+ MB

## Verificamos valores faltantes:

In [5]:
df.isnull()

,customerID,gender,SeniorCitizen,Partner,Dependents,Edad,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Duplicados:

In [7]:
# A nivel general:
df.duplicated().sum()

0

In [11]:
#a nivel de identificadores:
df.customerID.nunique()

7043

In [14]:
# Mostramos informacion de las variables categoricas:
for column in df.columns:
    if df[column].dtype == 'object':
        unique_value = df[column].unique()
        print(f'Columna:{column}')
        print(f'categorias:{unique_value}\n')

Columna:customerID
categorias:['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']

Columna:gender
categorias:['Female' 'Male']

Columna:Partner
categorias:['Yes' 'No']

Columna:Dependents
categorias:['No' 'Yes']

Columna:MultipleLines
categorias:['No phone service' 'No' 'Yes']

Columna:InternetService
categorias:['DSL' 'Fiber optic' 'No']

Columna:OnlineSecurity
categorias:['No' 'Yes' 'No internet service']

Columna:OnlineBackup
categorias:['Yes' 'No' 'No internet service']

Columna:DeviceProtection
categorias:['No' 'Yes' 'No internet service']

Columna:TechSupport
categorias:['No' 'Yes' 'No internet service']

Columna:StreamingTV
categorias:['No' 'Yes' 'No internet service']

Columna:StreamingMovies
categorias:['No' 'Yes' 'No internet service']

Columna:PhoneService
categorias:['No' 'Yes']

Columna:Contract
categorias:['Month-to-month' 'One year' 'Two year']

Columna:PaperlessBilling
categorias:['Yes' 'No']

Columna:PaymentMethod
categorias:['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

Columna:Churn
categorias:['No' 'Yes']

### NO se Observan variables con categorias √∫nicas,faltaria analizar despues la distribucion e importancia de cada una.

#### Existe una variable de tipo int que se comporta como categoria veamos las opciones:

In [17]:
jubilado = df['SeniorCitizen'].unique()
print(jubilado)

[0 1]

### Tiene dos categorias analizaremos despes la distribuci√≥n

In [19]:
df.to_csv('C:/Users/User/Proyecto Coder/data/processed/df_processed.csv')